/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ActivateTenantRequest
 */
public class ActivateTenantRequestTest {
    private final ActivateTenantRequest model = new ActivateTenantRequest();

    /**
     * Model tests for ActivateTenantRequest
     */
    @Test
    public void testActivateTenantRequest() {
        // TODO: test ActivateTenantRequest
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'companyAddress'
     */
    @Test
    public void companyAddressTest() {
        // TODO: test companyAddress
    }

    /**
     * Test the property 'companyCity'
     */
    @Test
    public void companyCityTest() {
        // TODO: test companyCity
    }

    /**
     * Test the property 'companyPostalCode'
     */
    @Test
    public void companyPostalCodeTest() {
        // TODO: test companyPostalCode
    }

    /**
     * Test the property 'companyCountry'
     */
    @Test
    public void companyCountryTest() {
        // TODO: test companyCountry
    }

    /**
     * Test the property 'companyOrgNumber'
     */
    @Test
    public void companyOrgNumberTest() {
        // TODO: test companyOrgNumber
    }

    /**
     * Test the property 'companyVATNumber'
     */
    @Test
    public void companyVATNumberTest() {
        // TODO: test companyVATNumber
    }

}
