/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateTenantRequest
 */
public class CreateTenantRequestTest {
    private final CreateTenantRequest model = new CreateTenantRequest();

    /**
     * Model tests for CreateTenantRequest
     */
    @Test
    public void testCreateTenantRequest() {
        // TODO: test CreateTenantRequest
    }

    /**
     * Test the property 'tenantName'
     */
    @Test
    public void tenantNameTest() {
        // TODO: test tenantName
    }

    /**
     * Test the property 'adminEmail'
     */
    @Test
    public void adminEmailTest() {
        // TODO: test adminEmail
    }

}
