/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ActivateTenantRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-27T12:28:31.876+02:00[Europe/Stockholm]")
public class ActivateTenantRequest {
  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  private String companyName;

  public static final String SERIALIZED_NAME_COMPANY_ADDRESS = "companyAddress";
  @SerializedName(SERIALIZED_NAME_COMPANY_ADDRESS)
  private String companyAddress;

  public static final String SERIALIZED_NAME_COMPANY_CITY = "companyCity";
  @SerializedName(SERIALIZED_NAME_COMPANY_CITY)
  private String companyCity;

  public static final String SERIALIZED_NAME_COMPANY_POSTAL_CODE = "companyPostalCode";
  @SerializedName(SERIALIZED_NAME_COMPANY_POSTAL_CODE)
  private String companyPostalCode;

  public static final String SERIALIZED_NAME_COMPANY_COUNTRY = "companyCountry";
  @SerializedName(SERIALIZED_NAME_COMPANY_COUNTRY)
  private String companyCountry;

  public static final String SERIALIZED_NAME_COMPANY_ORG_NUMBER = "companyOrgNumber";
  @SerializedName(SERIALIZED_NAME_COMPANY_ORG_NUMBER)
  private String companyOrgNumber;

  public static final String SERIALIZED_NAME_COMPANY_V_A_T_NUMBER = "companyVATNumber";
  @SerializedName(SERIALIZED_NAME_COMPANY_V_A_T_NUMBER)
  private String companyVATNumber;


  public ActivateTenantRequest companyName(String companyName) {
    
    this.companyName = companyName;
    return this;
  }

   /**
   * The full name of your company.
   * @return companyName
  **/
  @ApiModelProperty(required = true, value = "The full name of your company.")

  public String getCompanyName() {
    return companyName;
  }


  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }


  public ActivateTenantRequest companyAddress(String companyAddress) {
    
    this.companyAddress = companyAddress;
    return this;
  }

   /**
   * The first line of the address for your company.
   * @return companyAddress
  **/
  @ApiModelProperty(required = true, value = "The first line of the address for your company.")

  public String getCompanyAddress() {
    return companyAddress;
  }


  public void setCompanyAddress(String companyAddress) {
    this.companyAddress = companyAddress;
  }


  public ActivateTenantRequest companyCity(String companyCity) {
    
    this.companyCity = companyCity;
    return this;
  }

   /**
   * The city in which the address is located.
   * @return companyCity
  **/
  @ApiModelProperty(required = true, value = "The city in which the address is located.")

  public String getCompanyCity() {
    return companyCity;
  }


  public void setCompanyCity(String companyCity) {
    this.companyCity = companyCity;
  }


  public ActivateTenantRequest companyPostalCode(String companyPostalCode) {
    
    this.companyPostalCode = companyPostalCode;
    return this;
  }

   /**
   * The postal code for the address.
   * @return companyPostalCode
  **/
  @ApiModelProperty(required = true, value = "The postal code for the address.")

  public String getCompanyPostalCode() {
    return companyPostalCode;
  }


  public void setCompanyPostalCode(String companyPostalCode) {
    this.companyPostalCode = companyPostalCode;
  }


  public ActivateTenantRequest companyCountry(String companyCountry) {
    
    this.companyCountry = companyCountry;
    return this;
  }

   /**
   * The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).
   * @return companyCountry
  **/
  @ApiModelProperty(required = true, value = "The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).")

  public String getCompanyCountry() {
    return companyCountry;
  }


  public void setCompanyCountry(String companyCountry) {
    this.companyCountry = companyCountry;
  }


  public ActivateTenantRequest companyOrgNumber(String companyOrgNumber) {
    
    this.companyOrgNumber = companyOrgNumber;
    return this;
  }

   /**
   * Your company&#39;s organization number.
   * @return companyOrgNumber
  **/
  @ApiModelProperty(required = true, value = "Your company's organization number.")

  public String getCompanyOrgNumber() {
    return companyOrgNumber;
  }


  public void setCompanyOrgNumber(String companyOrgNumber) {
    this.companyOrgNumber = companyOrgNumber;
  }


  public ActivateTenantRequest companyVATNumber(String companyVATNumber) {
    
    this.companyVATNumber = companyVATNumber;
    return this;
  }

   /**
   * A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.
   * @return companyVATNumber
  **/
  @ApiModelProperty(required = true, value = "A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.")

  public String getCompanyVATNumber() {
    return companyVATNumber;
  }


  public void setCompanyVATNumber(String companyVATNumber) {
    this.companyVATNumber = companyVATNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateTenantRequest activateTenantRequest = (ActivateTenantRequest) o;
    return Objects.equals(this.companyName, activateTenantRequest.companyName) &&
        Objects.equals(this.companyAddress, activateTenantRequest.companyAddress) &&
        Objects.equals(this.companyCity, activateTenantRequest.companyCity) &&
        Objects.equals(this.companyPostalCode, activateTenantRequest.companyPostalCode) &&
        Objects.equals(this.companyCountry, activateTenantRequest.companyCountry) &&
        Objects.equals(this.companyOrgNumber, activateTenantRequest.companyOrgNumber) &&
        Objects.equals(this.companyVATNumber, activateTenantRequest.companyVATNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, companyAddress, companyCity, companyPostalCode, companyCountry, companyOrgNumber, companyVATNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateTenantRequest {\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    companyAddress: ").append(toIndentedString(companyAddress)).append("\n");
    sb.append("    companyCity: ").append(toIndentedString(companyCity)).append("\n");
    sb.append("    companyPostalCode: ").append(toIndentedString(companyPostalCode)).append("\n");
    sb.append("    companyCountry: ").append(toIndentedString(companyCountry)).append("\n");
    sb.append("    companyOrgNumber: ").append(toIndentedString(companyOrgNumber)).append("\n");
    sb.append("    companyVATNumber: ").append(toIndentedString(companyVATNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

