/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateTenantRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-27T12:28:31.876+02:00[Europe/Stockholm]")
public class CreateTenantRequest {
  public static final String SERIALIZED_NAME_TENANT_NAME = "tenantName";
  @SerializedName(SERIALIZED_NAME_TENANT_NAME)
  private String tenantName;

  public static final String SERIALIZED_NAME_ADMIN_EMAIL = "adminEmail";
  @SerializedName(SERIALIZED_NAME_ADMIN_EMAIL)
  private String adminEmail;


  public CreateTenantRequest tenantName(String tenantName) {
    
    this.tenantName = tenantName;
    return this;
  }

   /**
   * The name of the tenant should preferably be the name of your organization/company. Does not need to be but your end users will see this name.
   * @return tenantName
  **/
  @ApiModelProperty(example = "Example Company", required = true, value = "The name of the tenant should preferably be the name of your organization/company. Does not need to be but your end users will see this name.")

  public String getTenantName() {
    return tenantName;
  }


  public void setTenantName(String tenantName) {
    this.tenantName = tenantName;
  }


  public CreateTenantRequest adminEmail(String adminEmail) {
    
    this.adminEmail = adminEmail;
    return this;
  }

   /**
   * Email to the person that will be tenant admin.
   * @return adminEmail
  **/
  @ApiModelProperty(example = "admin@example.com", required = true, value = "Email to the person that will be tenant admin.")

  public String getAdminEmail() {
    return adminEmail;
  }


  public void setAdminEmail(String adminEmail) {
    this.adminEmail = adminEmail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTenantRequest createTenantRequest = (CreateTenantRequest) o;
    return Objects.equals(this.tenantName, createTenantRequest.tenantName) &&
        Objects.equals(this.adminEmail, createTenantRequest.adminEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantName, adminEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTenantRequest {\n");
    sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
    sb.append("    adminEmail: ").append(toIndentedString(adminEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

