/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

/**
 * payload with the secret key and url to QR code image
 */
@ApiModel(description = "payload with the secret key and url to QR code image")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-09-27T12:28:31.876+02:00[Europe/Stockholm]")
public class TotpEnableResponse {
  public static final String SERIALIZED_NAME_SECRET_KEY = "secretKey";
  @SerializedName(SERIALIZED_NAME_SECRET_KEY)
  private String secretKey;

  public static final String SERIALIZED_NAME_QR_IMAGE = "qrImage";
  @SerializedName(SERIALIZED_NAME_QR_IMAGE)
  private URI qrImage;


  public TotpEnableResponse secretKey(String secretKey) {
    
    this.secretKey = secretKey;
    return this;
  }

   /**
   * Get secretKey
   * @return secretKey
  **/
  @ApiModelProperty(required = true, value = "")

  public String getSecretKey() {
    return secretKey;
  }


  public void setSecretKey(String secretKey) {
    this.secretKey = secretKey;
  }


  public TotpEnableResponse qrImage(URI qrImage) {
    
    this.qrImage = qrImage;
    return this;
  }

   /**
   * Get qrImage
   * @return qrImage
  **/
  @ApiModelProperty(required = true, value = "")

  public URI getQrImage() {
    return qrImage;
  }


  public void setQrImage(URI qrImage) {
    this.qrImage = qrImage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TotpEnableResponse totpEnableResponse = (TotpEnableResponse) o;
    return Objects.equals(this.secretKey, totpEnableResponse.secretKey) &&
        Objects.equals(this.qrImage, totpEnableResponse.qrImage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secretKey, qrImage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TotpEnableResponse {\n");
    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
    sb.append("    qrImage: ").append(toIndentedString(qrImage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

