/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImagesApi
 */
@Ignore
public class ImagesApiTest {

    private final ImagesApi api = new ImagesApi();

    
    /**
     * Returns a generated QR code
     *
     * This endpoint does not do any lookups of any sort. It will just generate a QR code from the parameters supplied to it.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void imagesTotpTest() throws ApiException {
        String tenantName = null;
        String userId = null;
        String userSecret = null;
        File response = api.imagesTotp(tenantName, userId, userSecret);

        // TODO: test validations
    }
    
}
