/*
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateUserRequest;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.UpdateUserRequest;
import org.openapitools.client.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Creates a user in tenant, tenant is determined from the token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersCreateTest() throws ApiException {
        CreateUserRequest createUserRequest = null;
        User response = api.usersCreate(createUserRequest);

        // TODO: test validations
    }
    
    /**
     * Deletes specified user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersDeleteTest() throws ApiException {
        String userId = null;
        api.usersDelete(userId);

        // TODO: test validations
    }
    
    /**
     * Returns specified user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersGetTest() throws ApiException {
        String userId = null;
        User response = api.usersGet(userId);

        // TODO: test validations
    }
    
    /**
     * Updates specified user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usersUpdateTest() throws ApiException {
        String userId = null;
        UpdateUserRequest updateUserRequest = null;
        User response = api.usersUpdate(userId, updateUserRequest);

        // TODO: test validations
    }
    
}
